### PR TITLE
open list issue

### PR DESCRIPTION
**Pull request by ritishab0209**
Fixed the necessary problems in the open.bat file

### CODE REVIEW

**Comment by Bashamega** [comment]
Please add a description of the changes you made.

**Comment by ritishab0209** [comment]
I added 2^>nul to the reg query commands, which suppresses errors if the registry key isn't found.
Added a check to see if the variable is empty.
Added a condition in the for loop to ensure only non-empty AppPath values are echoed

**Review by Bashamega — CHANGES_REQUESTED** [review]
Still doesn't retrieve the apps: 
image

**Comment by ritishab0209** [comment]
Actually i am not able to reproduce the same error, maybe this is happening because the applications are listed in different registry paths

**Comment by ritishab0209** [comment]
Shall I look out for this path HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall

**Pull request closed without merging**
